routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/unlock', 'UnlockController@showLoginForm')->name('unlock');
Route::post('/unlock', 'UnlockController@login');

Route::middleware('auth.unlock')
    ->group(function() {
        Route::get('/lock', 'UnlockController@logout')->name('lock');

        Route::get('/', 'WelcomeController@index')->name('welcome');
        Route::post('/', 'WelcomeController@sendHour');
    });

Route::name('auth.')
    ->prefix('auth')
    ->namespace('Auth')
    ->group(function() {
        Route::get('login', 'LoginController@showLoginForm')->name('login');
        Route::post('login', 'LoginController@login');

        Route::get('logout', 'LoginController@logout')->name('logout')->middleware('auth');
    });

Route::get('/dashboard', 'DashboardController@index')->name('dashboard')->middleware('auth');
Route::name('dashboard.')
    ->prefix('dashboard')
    ->namespace('Dashboard')
    ->middleware('auth')
    ->group(function() {
        Route::get('/force_password_change', 'ForcePasswordChangeController@index')->name('force_password_change');
        Route::post('/force_password_change', 'ForcePasswordChangeController@update');

        Route::name('settings.')
            ->prefix('settings')
            ->namespace('Settings')
            ->group(function() {
                Route::get('/me', 'MeController@index')->name('me');
                Route::put('/me', 'MeController@update');

                Route::get('/system', 'SystemController@index')->name('system');
                Route::post('/system', 'SystemController@update');
            });

        Route::resource('users', 'UserController', ['except' => [
            'show'
        ]]);
    });

app/Setting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\File;

class Setting extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'key', 'value'
    ];

    /**
     * Default path to upload images
     *
     * @var string
     */
    protected $pathUpload = '/upload/application/';

    /**
     * Set the value of the setting.
     *
     * @param $value
     * @return string
     */
    public function setValueAttribute($value)
    {
        if ($value === '' || is_null($value)) {
            return $this->attributes['value'] = '';
        }

        if (! $value instanceof UploadedFile) {
            return $this->attributes['value'] = $value;
        }

        return $this->uploadImage($value);
    }

    /**
     * Get the setting value.
     *
     * @param $value
     * @return string
     */
    public function getValueAttribute($value)
    {
        if ($this->getAttribute('type') === 'image') {
            return $this->pathUpload . $value;
        }

        return $value;
    }

    /**
     * Upload the image to the server.
     *
     * @param $image
     * @return string
     */
    protected function uploadImage($image)
    {
        $oldImage = isset($this->attributes['value']) ? $this->attributes['value'] : null;

        if ($oldImage) {
            File::delete(public_path($oldImage));
        }

        $imageName = (str_random(15) . time()) . "." . $image->getClientOriginalExtension();
        $image->move(public_path() . $this->pathUpload, $imageName);

        $this->attributes['type'] = 'image';
        return $this->attributes['value'] = $imageName;
    }
}

app/Http/Controllers/Dashboard/ForcePasswordChangeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\Dashboard\UpdateForcePasswordChangeRequest;
use App\Http\Controllers\Controller;
use App\Repositories\UserRepository;

class ForcePasswordChangeController extends Controller
{
    /**
     * @var UserRepository
     */
    protected $users;

    /**
     * ForcePasswordChangeController constructor.
     *
     * @param UserRepository $users
     */
    public function __construct(UserRepository $users)
    {
        $this->users = $users;
    }

    /**
     * Form to force password change.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\View\View
     */
    public function index()
    {
        if (! auth()->user()->force_password_change) {
            $route = request()->url() == redirect()->back()->getTargetUrl() ? route('dashboard') : redirect()->back()->getTargetUrl();

            return redirect()->route('dashboard');
        }

        return view('dashboard.force_password_change');
    }

    /**
     * Update the password of the authenticated user.
     *
     * @param UpdateForcePasswordChangeRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateForcePasswordChangeRequest $request)
    {
        $this->users->update([
            'password' => $request->get('password'),
            'force_password_change' => false
        ], auth()->user()->id);

        return back();
    }
}

app/Http/Controllers/Dashboard/Settings/MeController.php
<?php

namespace App\Http\Controllers\Dashboard\Settings;

use App\Http\Requests\Dashboard\UpdateSettingRequest;
use App\Repositories\UserRepository;
use App\Http\Controllers\Controller;

class MeController extends Controller
{
    /**
     * @var UserRepository
     */
    protected $users;

    /**
     * MeController constructor.
     *
     * @param UserRepository $users
     */
    public function __construct(UserRepository $users)
    {
        $this->users = $users;
    }

    /**
     * Display a settings page from
     * authenticated user.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('dashboard.settings.me');
    }

    /**
     * Update the authenticated user
     * resource in storage.
     *
     * @param UpdateSettingRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateSettingRequest $request)
    {
        $user = $this->users->update(
            $request->only('name', 'email', 'password', 'image', 'language'),
            auth()->user()->id
        );

        return redirect()->back();
    }
}

app/Http/Controllers/Dashboard/Settings/SystemController.php
<?php

namespace App\Http\Controllers\Dashboard\Settings;

use App\Http\Requests\Dashboard\Settings\UpdateSystemRequest;
use App\Repositories\SettingRepository;
use App\Http\Controllers\Controller;
use App\Setting;

class SystemController extends Controller
{
    /**
     * @var SettingRepository
     */
    protected $settings;

    /**
     * SystemController constructor.
     *
     * @param SettingRepository $settings
     */
    public function __construct(SettingRepository $settings)
    {
        $this->settings = $settings;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $this->authorize('view', Setting::class);
        
        $settings = $this->settings->allByKeyValue();

        return view('dashboard.settings.system', compact('settings'));
    }

    /**
     * @param UpdateSystemRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateSystemRequest $request)
    {
        $this->authorize('update', Setting::class);
        
        $fields = $request->only('name', 'logo', 'default_language');
        $this->settings->syncKeys($fields);

        return back()->with('_updated', true);
    }
}

app/Http/Controllers/Dashboard/UserController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\Dashboard\Users\StoreUserRequest;
use App\Http\Requests\Dashboard\Users\UpdateUserRequest;
use App\Repositories\UserRepository;
use App\Http\Controllers\Controller;
use App\User;

class UserController extends Controller
{
    /**
     * @var UserRepository
     */
    protected $users;

    /**
     * UserController constructor.
     *
     * @param UserRepository $users
     */
    public function __construct(UserRepository $users)
    {
        $this->users = $users;
    }

    /**
     * Display a listing of the users.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $this->authorize('view', User::class);
        $users = $this->users->paginate(15);

        return view('dashboard.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new user.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $this->authorize('create', User::class);

        return view('dashboard.users.manipulate');
    }

    /**
     * Store a newly created user in storage.
     *
     * @param StoreUserRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StoreUserRequest $request)
    {
        $this->authorize('create', User::class);

        $fields = [
            'name' => $request->get('name'),
            'email' => $request->get('email'),
            'password' => $request->get('password'),
            'force_password_change' => $request->has('force_password_change'),
            'role' => $request->get('role'),
            'hour_control' => $request->has('hour_control'),
            'language' => $request->get('language'),
            'is_master' => $request->has('is_master')
        ];
        $this->users->create($fields);

        return back()->with('_stored', true);
    }

    /**
     * Show the form for editing the specified user.
     *
     * @param $user
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($user)
    {
        $this->authorize('update', User::class, $user);

        $user = $this->users->find($user);

        return view('dashboard.users.manipulate', compact('user'));
    }

    /**
     * Update the specified user in storage.
     *
     * @param UpdateUserRequest $request
     * @param $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateUserRequest $request, $user)
    {
        $this->authorize('update', User::class, $user);

        $fields = [
            'name' => $request->get('name'),
            'email' => $request->get('email'),
            'password' => $request->get('password'),
            'force_password_change' => $request->has('force_password_change'),
            'role' => $request->get('role'),
            'hour_control' => $request->has('hour_control'),
            'language' => $request->get('language'),
            'is_master' => $request->has('is_master')
        ];
        $this->users->update($fields, $user);

        return back()->with('_updated', true);
    }

    /**
     * Remove the specified user from storage.
     *
     * @param $user
     * @return string
     */
    public function destroy($user)
    {
        $this->authorize('delete', User::class, $user);

        $this->users->delete($user);

        return redirect()->route('dashboard.users.index');
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\UserRepository;

class DashboardController extends Controller
{
    /**
     * @var UserRepository
     */
    protected $users;

    /**
     * DashboardController constructor.
     *
     * @param UserRepository $users
     */
    public function __construct(UserRepository $users)
    {
        $this->users = $users;
    }

    /**
     * Show the application welcome page.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $users = $this->users->lastHours();

        return view('dashboard', compact('users'));
    }
}

resources/views/dashboard/settings/me.blade.php
@extends('layouts.app')

@section('content-header')
    <h1>{{ trans('message.my_account_settings') }}</h1>
@endsection

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <form action="{{ route('dashboard.settings.me') }}" method="post" enctype="multipart/form-data">
                <div class="box box-danger">
                    <div class="box-header with-border">
                        <h3 class="box-title">{{ auth()->user()->name }} - {{ trans('message.settings') }}</h3>
                    </div>

                    <div class="box-body">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}

                        <div class="row">
                            <div class="col-xs-4">
                                <div class="form-group {{ $errors->has('name') ? 'has-error' : null }}">
                                    <label for="form-name">{{ trans('form.field.full_name') }}</label>
                                    <input type="text"
                                           id="form-name"
                                           name="name"
                                           class="form-control"
                                           placeholder="{{ trans("form.placeholder.enter_full_name") }}"
                                           value="{{ auth()->user()->name }}"
                                    >

                                    @if ($errors->has('name'))
                                        <span class="help-block">{{ $errors->first('name') }}</span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-xs-5">
                                <div class="form-group {{ $errors->has('email') ? 'has-error' : null }}">
                                    <label for="form-email">{{ trans('form.field.email') }}</label>
                                    <input type="email"
                                           id="form-email"
                                           name="email"
                                           class="form-control"
                                           placeholder="{{ trans("form.placeholder.enter_email") }}"
                                           value="{{ auth()->user()->email }}"
                                    >

                                    @if ($errors->has('email'))
                                        <span class="help-block">{{ $errors->first('email') }}</span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-xs-3">
                                <div class="form-group {{ $errors->has('language') ? 'has-error' : null }}">
                                    <label for="form-language">{{ trans('form.field.language') }}</label>
                                    <select id="form-language"
                                            name="language"
                                            class="form-control"
                                    >
                                        <option value="en" {{ auth()->user()->language == 'en' ? 'selected' : '' }}>{{ trans('message.language.en') }}</option>
                                        <option value="pt-BR" {{ auth()->user()->language == 'pt-BR' ? 'selected' : '' }}>{{ trans('message.language.pt-BR') }}</option>
                                    </select>

                                    @if ($errors->has('language'))
                                        <span class="help-block">{{ $errors->first('language') }}</span>
                                    @endif
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-6">
                                <div class="form-group {{ $errors->has('password') ? 'has-error' : null }}">
                                    <label for="form-password">{{ trans('form.field.password') }}</label>
                                    <input type="password"
                                           id="form-password"
                                           name="password"
                                           class="form-control"
                                           placeholder="{{ trans("form.placeholder.enter_new_password") }}"
                                    >

                                    @if ($errors->has('password'))
                                        <span class="help-block">{{ $errors->first('password') }}</span>
                                    @endif
                                </div>
                            </div>

                            <div class="col-xs-6">
                                <div class="form-group {{ $errors->has('password_confirmation') ? 'has-error' : null }}">
                                    <label for="form-password-confirmation">{{ trans('form.field.confirm_password') }}</label>
                                    <input type="password"
                                           id="form-password-confirmation"
                                           name="password_confirmation"
                                           class="form-control"
                                           placeholder="{{ trans("form.placeholder.confirm_password") }}"
                                    >

                                    @if ($errors->has('password_confirmation'))
                                        <span class="help-block">{{ $errors->first('password_confirmation') }}</span>
                                    @endif
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-8">
                                <div class="form-group {{ $errors->has('image') ? 'has-error' : null }}">
                                    <label for="form-image">{{ trans('form.field.image') }}</label>
                                    <input type="file"
                                           id="form-image"
                                           name="image"
                                    >

                                    @if($errors->has('image'))
                                        <span class="help-block">{{ $errors->first('image') }}</span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-xs-4 text-center">
                                <img src="{{ asset(auth()->user()->image) }}" class="img-responsive">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox"> {{ trans('form.field.set_default_image') }}
                                    </label>
                                </div>
                            </div>
                        </div>

                    </div>

                    <div class="box-footer text-right">
                        <button type="submit" class="btn btn-success btn-sm">
                            <i class="fa fa-check"></i>
                            {{ trans('form.button.save') }}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/dashboard/settings/system.blade.php
@extends("layouts.app")

@section('content-header')
    <h1>{{ trans('message.system_settings') }}</h1>
@endsection

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <form action="{{ route('dashboard.settings.system') }}"
                  method="POST"
                  class="form-horizontal"
                  enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="box box-danger">
                    <div class="box-header">
                        <h3 class="box-title">{{ trans('message.configure_your_system') }}</h3>
                    </div>
                    <div class="box-body">
                        @if (session('_updated'))
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="alert alert-success">
                                        <strong>
                                            {{ trans('message.success.settings_system_updated') }}
                                        </strong>
                                    </div>
                                </div>
                            </div>
                        @endif

                        <div class="form-group {{ $errors->has('name') ? 'has-error' : null }}">
                            <label for="form-name" class="col-sm-2 control-label">{{ trans('form.field.application_name') }}</label>

                            <div class="col-sm-10">
                                <input type="text"
                                       id="form-name"
                                       name="name"
                                       class="form-control"
                                       placeholder="{{ trans("form.placeholder.enter_application_name") }}"
                                       value="{{ old('name') ? old('name') : $settings->get('name') }}"
                                >

                                @if ($errors->has('name'))
                                    <span class="help-block">{{ $errors->first('name') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group {{ $errors->has('logo') ? 'has-error' : null }}">
                            <label for="form-logo" class="col-sm-2 control-label">{{ trans('form.field.logo') }}</label>

                            <div class="col-sm-10">
                                <input type="file"
                                       id="form-logo"
                                       name="logo"
                                >

                                @if ($errors->has('logo'))
                                    <span class="help-block">{{ $errors->first('logo') }}</span>
                                @endif

                                @if($settings->get('logo'))
                                    <div class="col-xs-4" style="padding-top: 10px;">
                                        <img src="{{ asset($settings->get('logo')) }}" class="img-responsive" alt="Logo Application">
                                    </div>
                                @endif
                            </div>
                        </div>

                        <div class="form-group {{ $errors->has('default_language') ? 'has-error' : '' }}">
                            <label for="form-role" class="col-sm-2 control-label">{{ trans("form.field.default_language") }}</label>

                            <div class="col-sm-10">
                                <select id="form-default-language"
                                        name="default_language"
                                        class="form-control"
                                >
                                    <option value="en" {{ old('default_language') == 'en' || $settings->get('default_language') == 'en' ? 'selected' : '' }}>
                                        {{ trans('message.language.en') }}
                                    </option>
                                    <option value="pt-BR" {{ old('default_language') == 'pt-BR' || $settings->get('default_language') == 'pt-BR' ? 'selected' : '' }}>
                                        {{ trans('message.language.pt-BR') }}
                                    </option>
                                </select>

                                @if ($errors->has('default_language'))
                                    <span class="help-block">{{ $errors->first('default_language') }}</span>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="box-footer text-right">
                        <button type="submit" class="btn btn-sm btn-primary">
                            <i class="fa fa-check"></i>&nbsp;&nbsp;
                            {{ trans('form.button.save')  }}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    @if (isset($user))
        <div id="modalDestroy" class="modal fade modal-danger" role="dialog">
            <form action="{{ route('dashboard.users.destroy', $user->id) }}" method="post">
                {{ csrf_field() }}
                {{ method_field('DELETE') }}
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Você tem certeza?</h4>
                        </div>
                        <div class="modal-body">
                            <p>
                                Você tem certeza que deseja excluir o usuário <strong>{{ $user->name }}</strong>?
                                Esta ação não poderá ser desfeita
                            </p>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-danger" data-dismill="modal">
                                {{ trans('form.button.delete') }}
                            </button>
                            <button type="button" class="btn btn-primary" data-dismiss="modal">{{ trans('form.button.close') }}</button>
                        </div>
                    </div>

                </div>
            </form>
        </div>
    @endif
@endsection