routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/unlock', 'UnlockController@showLoginForm')->name('unlock');
Route::post('/unlock', 'UnlockController@login');

Route::middleware('auth.unlock')
    ->group(function() {
        Route::get('/lock', 'UnlockController@logout')->name('lock');

        Route::get('/', 'WelcomeController@index')->name('welcome');
        Route::post('/', 'WelcomeController@sendHour');
    });

Route::name('auth.')
    ->prefix('auth')
    ->namespace('Auth')
    ->group(function() {
        Route::get('login', 'LoginController@showLoginForm')->name('login');
        Route::post('login', 'LoginController@login');

        Route::get('logout', 'LoginController@logout')->name('logout')->middleware('auth');
    });

Route::get('/dashboard', 'DashboardController@index')->name('dashboard')->middleware('auth');
Route::name('dashboard.')
    ->prefix('dashboard')
    ->namespace('Dashboard')
    ->middleware('auth')
    ->group(function() {
        Route::get('/force_password_change', 'ForcePasswordChangeController@index')->name('force_password_change');
        Route::post('/force_password_change', 'ForcePasswordChangeController@update');

        Route::name('settings.')
            ->prefix('settings')
            ->namespace('Settings')
            ->group(function() {
                Route::get('/me', 'MeController@index')->name('me');
                Route::put('/me', 'MeController@update');

                Route::get('/system', 'SystemController@index')->name('system');
                Route::post('/system', 'SystemController@update');
            });

        Route::resource('users', 'UserController', ['except' => [
            'show'
        ]]);
    });

app/User.php
<?php

namespace App;

use App\Traits\Models\ImageTrait;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    use ImageTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'image', 'force_password_change', 'role', 'hour_control', 'language', 'is_master'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'force_password_change' => 'boolean',
        'hour_control' => 'boolean',
        'is_master' => 'boolean'
    ];

    /**
     * Default name for images being uploaded
     *
     * @var string
     */
    protected $defaultImage = 'default-user.png';

    /**
     * Default path to upload images
     *
     * @var string
     */
    protected $pathUpload = '/upload/avatars/';

    /**
     * Sets encryption in password.
     *
     * @param $value
     */
    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }

    /**
     * The user's role name.
     *
     * @return array|\Illuminate\Contracts\Translation\Translator|null|string
     */
    public function getRoleNameAttribute()
    {
        $role = $this->getAttribute('role');

        return trans("message.role.{$role}");
    }

    /**
     * User hours.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function hours()
    {
        return $this->hasMany('App\UsersHour', 'user_id', 'id');
    }
}

resources/views/layouts/app/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        {{ system_setting('name', 'app.name') }}
    </div>
    <strong>{{ trans('message.copyright') }} © 2017 <a href="https://github.com/omarkdev" target="_blank">omarkdev</a>.</strong> {{ trans('message.all_rights_reserved') }}.
</footer>

resources/views/layouts/app/header.blade.php
<header class="main-header">
    <a href="{{ route('dashboard') }}" class="logo">
        @if (! system_setting('logo') && system_setting('name', 'app.name'))
            <b>{{ system_setting('name', 'app.name') }}</b>
        @endif

        @if (system_setting('logo'))
            <img src="{{ asset(system_setting('logo')) }}"
                 alt="{{ system_setting('name', 'app.name') }}"
                 title="{{ system_setting('name', 'app.name') }}"
                 class="img-responsive"
                 style="max-height: 90%; margin: 0 auto 0 auto; padding-top: 2.5%;">
        @endif
    </a>

    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

                @can('receive-notifications', \App\User::class)
                    <notifications trans-show-notifications="{{ trans('form.field.show_notifications') }}"
                                   trans-no-notification="{{ trans('message.no_notification') }}"
                                   trans-singular-notifications="{{ trans('message.replace.singular_notifications', ['var' => 'number']) }}"
                                   trans-plural-notifications="{{ trans('message.replace.plural_notifications', ['var' => 'number']) }}"
                                   trans-notification-title="{{ trans('message.notification_title') }}"
                    ></notifications>
                @endcan

                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ asset(auth()->user()->image) }}" class="user-image" alt="User Image"/>
                        <span class="hidden-xs">{{ auth()->user()->name }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-header">
                            <img src="{{ asset(auth()->user()->image) }}" class="img-circle" alt="User Image" />
                            <p>
                                {{ auth()->user()->name }} - {{ auth()->user()->role_name }}
                                <small>{{ trans('message.registered_in') }} {{ auth()->user()->created_at->format('d/m/Y H:i') }}</small>
                            </p>
                        </li>

                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{{ route('dashboard.settings.me') }}" class="btn btn-default btn-flat">
                                    {{ trans('form.button.settings') }}
                                </a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ route('auth.logout') }}" class="btn btn-default btn-flat">
                                    {{ trans('form.button.exit') }}
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/layouts/app/sidebar.blade.php
<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ asset(auth()->user()->image)  }}" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p>{{ auth()->user()->name }}</p>
            </div>
        </div>

        <ul class="sidebar-menu">
            <li class="header">Menu</li>
            <li class="{{ menu_active('dashboard') }}">
                <a href="{{ route('dashboard') }}">
                    <i class="fa fa-dashboard"></i> {{ trans('menu.dashboard') }}
                </a>
            </li>
            @can('view', \App\User::class)
                <li class="{{ menu_active('dashboard/users', true) }}">
                    <a href="{{ route('dashboard.users.index') }}">
                        <i class="fa fa-users"></i> {{ trans('menu.users') }}
                    </a>
                </li>
            @endcan

            @can('view', \App\Setting::class)
                <li class="treeview {{ menu_active('dashboard/settings', true) }}">
                    <a href="#">
                        <i class="fa fa-cogs"></i> <span>{{ trans('menu.settings.title') }}</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{{ menu_active('dashboard/settings/me') }}">
                            <a href="{{ route('dashboard.settings.me') }}">
                                <i class="fa fa-circle-o"></i> {{ trans('menu.settings.me') }}
                            </a>
                        </li>

                        <li class="{{ menu_active('dashboard/settings/system') }}">
                            <a href="{{ route('dashboard.settings.system') }}">
                                <i class="fa fa-circle-o"></i> {{ trans('menu.settings.system') }}
                            </a>
                        </li>
                    </ul>
                </li>
            @endcan

            @cannot('view', \App\Setting::class)
                <li class="{{ menu_active('dashboard/settings/me') }}">
                    <a href="{{ route('dashboard.settings.me') }}">
                        <i class="fa fa-cogs"></i> {{ trans('menu.settings.title') }}
                    </a>
                </li>
            @endcannot
        </ul>
    </section>
</aside>